---
title: "Individual Differences Analysis"
author: "Kayleigh Ryherd"
date: "1/28/2019"
output: 
  html_document:
    toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(warning = FALSE)
```

# Load Data

```{r load_data}
setwd("~/dissertation/DataAnalysis/Exp2")
ashby1 <- read.csv("./data_files/Ashby_concat_fall2018.csv")
ashby2 <- read.csv("./data_files/Ashby_concat_03-08-19_1626.csv")
colnames(ashby1)[3] <- "Run"
colnames(ashby1)[6] <- "key_pressed"
ashby <- rbind(ashby1,ashby2)
sloutsky <- read.csv("./data_files/Sloutsky_concat_03-08-19_1638.csv")
taxthem <- read.csv("./data_files/taxthem_concat_03-08-19_1637.csv")
tol <- read.csv("./data_files/tol_concat_03-11-19_1127.csv")
switcher <- read.csv("./data_files/switcher_concat_03-11-19_1127.csv")
flanker <- read.csv("./data_files/flanker_concat_03-11-19_1127.csv")
ravens <- read.csv("./data_files/ravens_3-11-19.csv")
nd <- read.csv("./data_files/ND_scores_3-8-19.csv")
nd_norms <- read.csv("./data_files/nd_norms.csv")
celf <- read.csv("./data_files/celf_3-11-19.csv")
age_gender <- read.csv("./data_files/age_gender_3-11-19.csv")
```

```{r libraries}
library(operators)
library(tidyverse)
library(ggcorrplot)
library(lme4)
library(lmerTest)
library(fBasics)
library(caret)
```


# Data Cleaning

## Category Learning Tasks

### Ashby

```{r}
# check block names
levels(as.factor(ashby$Run))
# edit typo
ashby$Run[ashby$Run == 33] <- 3
# create across-Run trial value
ashby$Overall_Trial <- (ashby$Run-1)*80 + ashby$Trial
# select only Runs 1 - 3
ashby_filt <- dplyr::filter(ashby, Run <= 3)
# select only people with complete data
complete <- ashby_filt %>% 
  group_by(Subject, Type) %>% 
  summarise(count = n()) %>% 
  dplyr::filter(count == 240) %>%
  spread(key = Type, value = count) %>%
  na.omit
nrow(complete)
complete_ashby_Runs <- complete$Subject
ashby_full <- ashby_filt %>%
  dplyr::filter(Subject %in% complete_ashby_Runs)
######### ACCURACY
# mean accuracy by subject and system
ashby_acc_long <- ashby_full %>%
  group_by(Subject, Type) %>%
  summarise(m_acc = mean(Accuracy))

# select new data frame
ashby_acc_stand <- ashby_acc_long
# z-scores
ashby_acc_stand$acc_z <- scale(ashby_acc_stand$m_acc)
# create column for system
ashby_acc_stand$System <- NA
ashby_acc_stand$System[ashby_acc_stand$Type == "II"] <- "associative"
ashby_acc_stand$System[ashby_acc_stand$Type == "RB"] <- "hypothesis-testing"
# create column for paradigm
ashby_acc_stand$CatLearn <- "ashby"
# create df with raw ACC values
ashby_acc <- ashby_acc_stand[,-c(2,4)]
# create df with ACC z-scores
ashby_acc_stand <- ashby_acc_stand[,-c(2,3)]

########### RT
# filter RTs and then calculate mean RT by subject
ashby_rt_long <- ashby_full %>%
  dplyr::filter(Accuracy == 1, RT > 0) %>% # selecting correct trials only, RTs > 0
  group_by(Subject, Type) %>%
  mutate(mean_rt = mean(RT),
         sd_rt = sd(RT),
         diff = RT-mean_rt,
         remove = ifelse(abs(diff) > 2*sd_rt, 1, 0)) %>% # if any trial has an RT more than 2SD away from the mean, flag it for removal
  dplyr::filter(remove == 0, Run == 3) %>% # remove those trials, choose only Run 3
  summarise(m_rt = mean(RT))

# remove outlier
ashby_rt_long <- ashby_rt_long %>%
  dplyr::filter(Subject != 8088)

# select new df
ashby_rt_stand <- ashby_rt_long
# create z-scores
ashby_rt_stand$rt_z <- scale(ashby_rt_stand$m_rt)
# create column for system
ashby_rt_stand$System <- NA
ashby_rt_stand$System[ashby_rt_stand$Type == "II"] <- "associative"
ashby_rt_stand$System[ashby_rt_stand$Type == "RB"] <- "hypothesis-testing"
# create column for paradigm
ashby_rt_stand$CatLearn <- "ashby"
# df with raw RTs
ashby_rt <- ashby_rt_stand[,-c(2,4)]
# df with RT z-scores
ashby_rt_stand <- ashby_rt_stand[,-c(2:3)]
```

### Sloutsky

```{r}
########## ACCURACY
poor_blocks <- sloutsky %>%
  dplyr::filter(substr(Stimulus,1,5) =="catch") %>%
  group_by(Subject,Block) %>%
  summarise(catch_acc = mean(Accuracy)) %>%
  dplyr::filter(catch_acc < 0.75) %>%
  mutate(subj_block = paste0(as.character(Subject), as.character(Block)))

# summarize ACCs by subject and system
sloutsky_acc_long <- sloutsky %>%
  mutate(subj_block = paste0(as.character(Subject), as.character(Block))) %>%
  dplyr::filter(subj_block %!in% poor_blocks$subj_block) %>%
  group_by(Subject, Block) %>%
  summarise(m_acc = mean(Accuracy))

slout_acc_stand <- sloutsky_acc_long %>%
  dplyr::filter(Block == "SupervisedSparse" | Block == "UnsupervisedDense") %>%
  dplyr::select(Subject, Block, m_acc)
# z-scores
slout_acc_stand$acc_z <- scale(slout_acc_stand$m_acc)
# create column for system
slout_acc_stand$System <- NA
slout_acc_stand$System[slout_acc_stand$Block == "UnsupervisedDense"] <- "associative"
slout_acc_stand$System[slout_acc_stand$Block == "SupervisedSparse"] <- "hypothesis-testing"
# create column for paradigm
slout_acc_stand$CatLearn <- "sloutsky"
# df with raw acc
slout_acc <- slout_acc_stand[,-c(2,4)]
# df with acc z-scores
slout_acc_stand <- slout_acc_stand[,-c(2,3)]

################## RT

# recode non-answers to missing
sloutsky$RT[sloutsky$RT == 9999] <- NA

# same RT processing as above
sl_rt <- sloutsky %>%
  mutate(subj_block = paste0(as.character(Subject), as.character(Block))) %>%
  dplyr::filter(subj_block %!in% poor_blocks$subj_block) %>%
  dplyr::filter(Accuracy == 1) %>%
  group_by(Subject, Block) %>%
  mutate(mean_rt = mean(RT),
         sd_rt = sd(RT),
         diff = RT-mean_rt,
         remove = ifelse(abs(diff) > 2*sd_rt, 1, 0)) %>%
  dplyr::filter(remove == 0) %>%
  summarise(m_rt = mean(RT))

sl_filt <- dplyr::filter(sl_rt, Block %in% c("UnsupervisedDense","SupervisedSparse"))
slout_rt_stand <- sl_filt
# z-scores
slout_rt_stand$rt_z <- scale(slout_rt_stand$m_rt)
# column for system
slout_rt_stand$System <- NA
slout_rt_stand$System[slout_rt_stand$Block == "UnsupervisedDense"] <- "associative"
slout_rt_stand$System[slout_rt_stand$Block == "SupervisedSparse"] <- "hypothesis-testing"
# column for paradigm
slout_rt_stand$CatLearn <- "sloutsky"
# df for raw RT
slout_rt <- slout_rt_stand[,-c(2,4)]
# df for RT z-scores
slout_rt_stand <- slout_rt_stand[,-c(2,3)]
```

### Tax/Them

```{r}
############ ACCURACY
# select only the test trials
test_trials <- dplyr::filter(taxthem, !is.na(expTrials.thisTrialN))

# calculate mean acc by participant and system
tt_acc <- test_trials %>%
  group_by(participant, Experiment) %>%
  summarise(m_acc = mean(resp.corr))
# new df
tt_acc_stand <- tt_acc
# rename column
colnames(tt_acc_stand)[1] <- "Subject"
# z-score
tt_acc_stand$acc_z <- scale(tt_acc_stand$m_acc)
# column for system
tt_acc_stand$System <- NA
tt_acc_stand$System[tt_acc_stand$Experiment == "thematic"] <- "hypothesis-testing"
tt_acc_stand$System[tt_acc_stand$Experiment == "taxonomic"] <- "associative"
# column for paradigm
tt_acc_stand$CatLearn <- "tt"
# df for raw acc
tt_acc <- tt_acc_stand[,-c(2,4)]
# df for acc z-score
tt_acc_stand <- tt_acc_stand[,-c(2,3)]


############ RT

# same RT processing as above
tt_rt <- test_trials %>%
  dplyr::filter(resp.corr == 1) %>%
  group_by(participant, Experiment) %>%
  mutate(mean_rt = mean(resp.rt),
         sd_rt = sd(resp.rt),
         diff = resp.rt-mean_rt,
         remove = ifelse(abs(diff) > 2*sd_rt, 1, 0)) %>%
  dplyr::filter(remove == 0) %>%
  summarise(m_rt = mean(resp.rt))

# 8147 and 8048 are clear outliers in both conditions, so I will remove them.
tt_rt <- dplyr::filter(tt_rt, participant != 8147, participant != 8048)

# new df
tt_rt_stand <- tt_rt
# rename column
colnames(tt_rt_stand)[1] <- "Subject"
# z-score
tt_rt_stand$rt_z <- scale(tt_rt_stand$m_rt)
# column for system
tt_rt_stand$System <- NA
tt_rt_stand$System[tt_rt_stand$Experiment == "thematic"] <- "hypothesis-testing"
tt_rt_stand$System[tt_rt_stand$Experiment == "taxonomic"] <- "associative"
# column for paradigm
tt_rt_stand$CatLearn <- "tt"
# df for raw rts
tt_rt <- tt_rt_stand[,-c(2,4)]
# df for rt z-scores
tt_rt_stand <- tt_rt_stand[,-c(2,3)]
```

### Combining 3 tasks - Accuracy

```{r}
# merge the data frames together
acc_long <- dplyr::bind_rows(ashby_acc, slout_acc, tt_acc)
acc_wide <- acc_long %>%
  spread(key = CatLearn, value = m_acc)

# test the normality of the different variables
dagoTest(acc_wide$ashby)
dagoTest(acc_wide$sloutsky)
dagoTest(acc_wide$tt)

# sloutsky and tt are skewed, so let's transform. ashby is almost skewed, why not.
vars_tf <- c("ashby","sloutsky", "tt")
# transformations
pp_md_tf <- caret::preProcess(as.data.frame(acc_wide[,vars_tf]), method = c("center", "scale", "YeoJohnson"), na.remove=T)
tf_data <- predict(pp_md_tf, as.data.frame(acc_wide[,vars_tf]))
# re-check normality
dagoTest(tf_data$ashby)
dagoTest(tf_data$sloutsky)
dagoTest(tf_data$tt)
# less skewed at least

# move data into main data frame
acc_wide$ashby.t <- tf_data$ashby
acc_wide$sloutsky.t <- tf_data$sloutsky
acc_wide$tt.t <- tf_data$tt

ashby_acc <- acc_wide %>%
  dplyr::select(Subject, System, ashby.t) %>%
  spread(key = System, value = ashby.t) %>%
  na.omit %>%
  gather(key = "System", value = "ashby.t", associative:`hypothesis-testing`)

sloutsky_acc <- acc_wide %>%
  dplyr::select(Subject, System, sloutsky.t) %>%
  spread(key = System, value = sloutsky.t) %>%
  na.omit %>%
  gather(key = "System", value = "sloutsky.t", associative:`hypothesis-testing`)

tt_acc <- acc_wide %>%
  dplyr::select(Subject, System, tt.t) %>%
  spread(key = System, value = tt.t) %>%
  na.omit %>%
  gather(key = "System", value = "tt.t", associative:`hypothesis-testing`)
```

### Combining 3 tasks - RT

```{r}
# merge the data frames together
rt_long <- dplyr::bind_rows(ashby_rt, slout_rt, tt_rt)
rt_wide <- rt_long %>%
  spread(key = CatLearn, value = m_rt)

# test the normality of the different variables
dagoTest(rt_wide$ashby)
dagoTest(rt_wide$sloutsky)
dagoTest(rt_wide$tt)

# all are skewed, let's transform
vars_tf <- c("ashby","sloutsky", "tt")
# transformations
pp_md_tf <- caret::preProcess(as.data.frame(rt_wide[,vars_tf]), method = c("center", "scale", "YeoJohnson"), na.remove=T)
tf_data <- predict(pp_md_tf, as.data.frame(rt_wide[,vars_tf]))
# re-check normality
dagoTest(tf_data$ashby)
dagoTest(tf_data$sloutsky)
dagoTest(tf_data$tt)
# less skewed at least

# move data into main data frame
rt_wide$ashby.t <- tf_data$ashby
rt_wide$sloutsky.t <- tf_data$sloutsky
rt_wide$tt.t <- tf_data$tt

ashby_rt <- rt_wide %>%
  dplyr::select(Subject, System, ashby.t) %>%
  spread(key = System, value = ashby.t) %>%
  na.omit %>%
  gather(key = "System", value = "ashby.t", associative:`hypothesis-testing`)

sloutsky_rt <- rt_wide %>%
  dplyr::select(Subject, System, sloutsky.t) %>%
  spread(key = System, value = sloutsky.t) %>%
  na.omit %>%
  gather(key = "System", value = "sloutsky.t", associative:`hypothesis-testing`)

tt_rt <- rt_wide %>%
  dplyr::select(Subject, System, tt.t) %>%
  spread(key = System, value = tt.t) %>%
  na.omit %>%
  gather(key = "System", value = "tt.t", associative:`hypothesis-testing`)
```

## Executive Function Measures

### Flanker
```{r flanker_calc}
# fix subject numbers
flanker$subnum[flanker$subnum==1] <- 8076
flanker$subnum[flanker$subnum==7] <- 8001
flanker$subnum[flanker$subnum==9] <- 8002
flanker$subnum[flanker$subnum==4] <- 8003
flanker$subnum[flanker$subnum==11] <- 8114
flanker$subnum[flanker$subnum==21] <- 8021
flanker$subnum[flanker$subnum==29] <- 8036
flanker$subnum[flanker$subnum==44] <- 8054
flanker$subnum[flanker$subnum==50] <- 8064
flanker$subnum[flanker$subnum==84] <- 8124
flanker$subnum[flanker$subnum==86] <- 8125
flanker$subnum[flanker$subnum==87] <- 8126
flanker$subnum[flanker$subnum==95] <- 8144

# remove non-responses
flanker <- subset(flanker, resp=="<lshift>" | resp=="<rshift>")

flanker_acc <- flanker %>%
  dplyr::filter(flankercoherence=="-1" | flankercoherence=="1") %>%
  group_by(subnum, flankercoherence) %>%
  summarise(acc = mean(corr, na.rm = TRUE)) %>%
  mutate(flankercoherence = ifelse(flankercoherence == -1, "incongruent", "congruent")) %>%
  spread(key = flankercoherence, value = acc) %>%
  mutate(flanker_eff_acc = congruent - incongruent)

#remove incorrect responses
flanker_cor <- subset(flanker, corr==1)

#subset for only coherent and incoherent trials
flanker_trim <- subset(flanker_cor, flankercoherence=="-1" | flankercoherence=="1")
flanker_trim$flankercoherence <- ifelse(flanker_trim$flankercoherence=="1", "flanker_congruent", "flanker_incongruent")

# calculate flanker effect
flanker_subject <- flanker_trim %>%
  group_by(subnum, flankercoherence) %>%
  summarise(flank_rt = mean(rt, na.rm = TRUE)) %>%
  spread(key = flankercoherence, value = flank_rt) %>%
  mutate(flanker_eff = flanker_incongruent - flanker_congruent)
```

### Switcher

```{r switcher_calc}
# fix subject numbers
switcher$subNum[switcher$subNum==1] <- 8076
switcher$subNum[switcher$subNum==7] <- 8001
switcher$subNum[switcher$subNum==9] <- 8002
switcher$subNum[switcher$subNum==4] <- 8003
switcher$subNum[switcher$subNum==11] <- 8114
switcher$subNum[switcher$subNum==21] <- 8021
switcher$subNum[switcher$subNum==29] <- 8036
switcher$subNum[switcher$subNum==44] <- 8054
switcher$subNum[switcher$subNum==50] <- 8064
switcher$subNum[switcher$subNum==84] <- 8124
switcher$subNum[switcher$subNum==86] <- 8125
switcher$subNum[switcher$subNum==87] <- 8126
switcher$subNum[switcher$subNum==95] <- 8144

switcher_subject <- switcher %>%
  group_by(subNum, testtype) %>%
  summarise(total_err = sum(numerr),
            total_time = sum(perftime),
            m_rt = mean(medtime))

switcher_totaltime <- switcher_subject %>%
  dplyr::select(subNum, testtype, total_time) %>%
  spread(key = testtype, value = total_time) %>%
  mutate(switcher_twofeat = `1`,
         switcher_threefeat = `2`,
         switcher_threefeatrand = `3`,
         switch_eff = `3` - `2`) %>% # basically the same as incongruent - congruent
  dplyr::select(subNum, switcher_twofeat:switch_eff)

switcher_errors <- switcher_subject %>%
  dplyr::select(subNum, testtype, total_err) %>%
  spread(key = testtype, value = total_err) %>%
  mutate(switcher_twofeat = `1`/36,
         switcher_threefeat = `2`/36,
         switcher_threefeatrand = `3`/36,
         switch_eff_err = switcher_threefeatrand - switcher_threefeat) %>% # basically the same as incongruent - congruent
  dplyr::select(subNum, switcher_twofeat:switch_eff_err)

```

### Tower of London

```{r tol_calc}
# fix subject numbers
tol$sub[tol$sub==1] <- 8076
tol$sub[tol$sub==7] <- 8001
tol$sub[tol$sub==9] <- 8002
tol$sub[tol$sub==4] <- 8003
tol$sub[tol$sub==11] <- 8114
tol$sub[tol$sub==21] <- 8021
tol$sub[tol$sub==29] <- 8036
tol$sub[tol$sub==44] <- 8054
tol$sub[tol$sub==50] <- 8064
tol$sub[tol$sub==84] <- 8124
tol$sub[tol$sub==86] <- 8125
tol$sub[tol$sub==87] <- 8126
tol$sub[tol$sub==95] <- 8144

tol_acc <- tol %>%
  group_by(sub) %>%
  summarise(m_acc = sum(success)/12)

# manual edit because these people got too many ToL trials
tol_acc$m_acc[tol_acc$sub == 8057] <- 1.00
tol_acc$m_acc[tol_acc$sub == 8002] <- 0.33

tol_time <- tol %>%
  dplyr::filter(success == 1) %>%
  group_by(sub) %>%
  summarise(m_planratio = mean(firsttime/time, na.rm = TRUE))

tol_calc <- inner_join(tol_acc,tol_time)
```

## Nelson-Denny

```{r nd_calc}
nd_standard <- nd %>%
  inner_join(.,nd_norms, by = c("Score" = "Raw.Score")) %>%
  rename(nd_raw = Score, nd_ss = Standard.score)
```

## Merge all ID measures together

```{r merge_ids}
fl_sw <- full_join(flanker_subject, switcher_totaltime, by = c("subnum" = "subNum"))
sw_tol <- full_join(fl_sw, tol_calc, by = c("subnum" = "sub"))
tol_nd <- full_join(sw_tol, nd_standard, by = c("subnum" = "Subject")) %>%
  rename(tol_acc = m_acc, tol_time = m_planratio)
nd_celf <- full_join(tol_nd, celf, by = c("subnum" = "Subject"))
#ra1 <- full_join(tol_nd, flanker_acc, by = "subnum")
#ra2 <- full_join(ra1, switcher_errors, by = c("subnum" = "subNum"))
id <- full_join(nd_celf, ravens, by = c("subnum" = "Subject.Number")) %>%
  rename(Subject = subnum, ravens = Score)
```

```{r check_transform}
for (i in 2:17){
  name <- names(id)[i]
  plot <- hist(as.data.frame(id)[,i], main = name)
  plot
  dago <- fBasics::dagoTest(as.data.frame(id)[,i])
  skewp <- dago@test$p.value[[2]]
  if (skewp <= 0.05){
    cat(name, " is skewed. p = ", round(skewp, 6), "\n")
  } else{
    cat(name, " is not skewed. p = ", round(skewp, 6), "\n")
  }
}

# transform switch_eff, tol_acc, tol_time, nd_ss, ravens, fs, rs
vars_tf <- c("switch_eff", "tol_acc", "tol_time", "nd_ss", "ravens", "rs_ss", "fs_ss")
pp_md_tf <- preProcess(as.data.frame(id)[,vars_tf], method = c("center", "scale", "YeoJohnson"), na.remove=T)
tf_data <- predict(pp_md_tf, as.data.frame(id)[,vars_tf])
names(tf_data) <- c("switch_eff_tf", "tol_acc_tf", "tol_time_tf", "nd_tf", "ravens_tf", "rs_tf", "fs_tf")
id <- cbind(as.data.frame(id),tf_data)

# scale and center flanker
id$flanker_eff_cs <- scale(id$flanker_eff)[,1]
```


```{r cor_plot}
# correlation matrix
cor_plot_dat <- dplyr::select(id, flanker_eff_cs, switch_eff_tf,tol_acc_tf, tol_time_tf, nd_tf, ravens_tf, rs_tf, fs_tf)
cor.mat <- cor(cor_plot_dat, use = "complete.obs")
p.mat <- cor_pmat(cor_plot_dat)
# plot
ggcorrplot(cor.mat, type = "lower", p.mat = p.mat, lab = TRUE)
```

# Descriptives

```{r}
nrow(age_gender)
age_gender$Gender <- as.character(age_gender$Gender)
age_gender$Gender[age_gender$Gender == "female"] <- "Female"
age_gender$Gender[age_gender$Gender == "male"] <- "Male"
age_gender$Gender <- as.factor(age_gender$Gender)
table(age_gender$Gender)
mean(age_gender$Age, na.rm = TRUE)
```

```{r}
id %>%
  dplyr::select(Subject, flanker_eff, switch_eff, tol_acc, nd_ss, rs_ss, fs_ss, ravens) %>%
  gather(key = "measure", value = "value", flanker_eff:ravens) %>%
  group_by(measure) %>%
  summarise(m = mean(value, na.rm = TRUE),
            sd = sd(value, na.rm = TRUE),
            min = min(value, na.rm = TRUE),
            max = max(value, na.rm = TRUE))
```

```{r}
acc_wide %>%
  dplyr::select(Subject:tt) %>%
  gather(key = "task", value = "value", ashby:tt) %>%
  mutate(task = paste0(task, "_", System)) %>%
  group_by(task) %>%
  summarise(m = mean(value, na.rm = TRUE),
            sd = sd(value, na.rm = TRUE),
            min = min(value, na.rm = TRUE),
            max = max(value, na.rm = TRUE))

rt_wide %>%
  dplyr::select(Subject:tt) %>%
  gather(key = "task", value = "value", ashby:tt) %>%
  mutate(task = paste0(task, "_", System)) %>%
  group_by(task) %>%
  summarise(m = mean(value, na.rm = TRUE),
            sd = sd(value, na.rm = TRUE),
            min = min(value, na.rm = TRUE),
            max = max(value, na.rm = TRUE))
```

# Accuracy Analysis

## Ashby

```{r ashby_acc}
ashby_acc_id <- merge(ashby_acc, id, by = "Subject", all.x = TRUE, all.y = FALSE)

ashby_dat <- ashby_acc_id %>%
  dplyr::select(Subject, System, ashby.t, flanker_eff_cs, switch_eff_tf, tol_acc_tf, nd_tf, ravens_tf) %>% 
  na.omit %>%
  head(264)  # take first 132 with full data 

m0 <- lmer(ashby.t ~ 1 + (1|Subject), data = ashby_dat)
m1 <- lmer(ashby.t ~ System + (1|Subject), data = ashby_dat)
anova(m0,m1)
#m2 <- lmer(ashby.t ~ System + ravens_tf + (1|Subject), data = ashby_dat)
#anova(m1,m2)
#anova(m2)
m3 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf  + (1|Subject), data = ashby_dat)
anova(m1,m3)
anova(m3)
m4.1 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + flanker_eff_cs:System + (1|Subject), data = ashby_dat)
anova(m3, m4.1)
m4.2 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + switch_eff_tf:System + (1|Subject), data = ashby_dat)
anova(m3, m4.2)
m4.3 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + tol_acc_tf:System + (1|Subject), data = ashby_dat)
anova(m3, m4.3)
m4.4 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + nd_tf:System + (1|Subject), data = ashby_dat)
anova(m3, m4.4)
anova(m4.4)

ht <- ashby_dat$System=="hypothesis-testing"
as <- ashby_dat$System=="associative"

ht_mod <- lm(ashby.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = ashby_dat, subset = ht)
summary(ht_mod)
anova(ht_mod)

as_mod <- lm(ashby.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = ashby_dat, subset = as)
summary(as_mod)
anova(as_mod)

ggplot(ashby_dat, aes(nd_tf, ashby.t)) + geom_point() + theme_bw() + facet_grid(.~System) + stat_smooth(method = "lm", se = FALSE)

# CELF ANALYSES

ashby_dat2 <- ashby_acc_id %>%
  dplyr::select(Subject, System, ashby.t, rs_tf, fs_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(ashby.t ~ 1 + (1|Subject), data = ashby_dat2)
m1 <- lmer(ashby.t ~ System + ravens_tf + (1|Subject), data = ashby_dat2)
anova(m0,m1)
m3 <- lmer(ashby.t ~ System + ravens_tf + rs_tf + fs_tf  + (1|Subject), data = ashby_dat2)
anova(m1,m3)
anova(m3)
```


## Sloutsky

```{r sloutsky_acc}
sloutsky_acc_id <- merge(sloutsky_acc, id, by = "Subject", all.x = TRUE, all.y = FALSE)

sloutsky_dat <- sloutsky_acc_id %>%
  dplyr::select(Subject, System, sloutsky.t, flanker_eff_cs, switch_eff_tf, tol_acc_tf, tol_time_tf, nd_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(sloutsky.t ~ 1 + (1|Subject), data = sloutsky_dat)
m1 <- lmer(sloutsky.t ~ System + (1|Subject), data = sloutsky_dat)
anova(m0,m1)
#m2 <- lmer(sloutsky.t ~ System + ravens_tf + (1|Subject), data = sloutsky_dat)
#anova(m1,m2)
#anova(m2)
m3 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf  + (1|Subject), data = sloutsky_dat)
anova(m1,m3)
anova(m3)
summary(m3)
m4.1 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + flanker_eff_cs:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.1)
m4.2 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + switch_eff_tf:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.2)
m4.3 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + tol_acc_tf:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.3)
m4.4 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + nd_tf:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.4)


ggplot(sloutsky_dat, aes(flanker_eff_cs, sloutsky.t)) + geom_point() + theme_bw() + stat_smooth(se = FALSE, method = "lm") + xlab("Flanker Effect") + ylab("Sloutsky Accuracy") + ggtitle("Significant main effect of flanker on Sloutsky accuracy")

ggplot(sloutsky_dat, aes(switch_eff_tf, sloutsky.t)) + geom_point() + theme_bw() + stat_smooth(se = FALSE, method = "lm") + xlab("Switcher Effect") + ylab("Sloutsky Accuracy") + ggtitle("Significant main effect of switcher on Sloutsky accuracy")


# CELF ANALYSES

sloutsky_dat2 <- sloutsky_acc_id %>%
  dplyr::select(Subject, System, sloutsky.t, rs_tf, fs_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(sloutsky.t ~ 1 + (1|Subject), data = sloutsky_dat2)
m1 <- lmer(sloutsky.t ~ System + ravens_tf + (1|Subject), data = sloutsky_dat2)
anova(m0,m1)
m3 <- lmer(sloutsky.t ~ System + ravens_tf + rs_tf + fs_tf  + (1|Subject), data = sloutsky_dat2)
anova(m1,m3)
anova(m3)
```


## TT

```{r tt_acc}
tt_acc_id <- merge(tt_acc, id, by = "Subject", all.x = TRUE, all.y = FALSE)

tt_dat <- tt_acc_id %>%
  dplyr::select(Subject, System, tt.t, flanker_eff_cs, switch_eff_tf, tol_acc_tf, tol_time_tf, nd_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(tt.t ~ 1 + (1|Subject), data = tt_dat)
m1 <- lmer(tt.t ~ System + (1|Subject), data = tt_dat)
anova(m0,m1)
#m2 <- lmer(tt.t ~ System + ravens_tf + (1|Subject), data = tt_dat)
#anova(m1,m2)
#anova(m2)
m3 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf  + (1|Subject), data = tt_dat)
anova(m1,m3)
anova(m3)
summary(m3)
m4.1 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + flanker_eff_cs:System + (1|Subject), data = tt_dat)
anova(m3, m4.1)
m4.2 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + switch_eff_tf:System + (1|Subject), data = tt_dat)
anova(m3, m4.2)
m4.3 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + tol_acc_tf:System + (1|Subject), data = tt_dat)
anova(m3, m4.3)
m4.4 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + nd_tf:System + (1|Subject), data = tt_dat)
anova(m3, m4.4)

ggplot(tt_dat, aes(tol_acc_tf, tt.t)) + geom_point(alpha = 0.25) + theme_bw() + stat_smooth(se = FALSE, method = "lm") + xlab("Planning (Tower of London accuracy)") + ylab("TT Accuracy") + ggtitle("Significant main effect of nonverbal IQ on TT accuracy")

# CELF ANALYSES

tt_dat2 <- tt_acc_id %>%
  dplyr::select(Subject, System, tt.t, rs_tf, fs_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(tt.t ~ 1 + (1|Subject), data = tt_dat2)
m1 <- lmer(tt.t ~ System + ravens_tf + (1|Subject), data = tt_dat2)
anova(m0,m1)
m3 <- lmer(tt.t ~ System + ravens_tf + rs_tf + fs_tf  + (1|Subject), data = tt_dat2)
anova(m1,m3)
anova(m3)
```

# RT Analysis

## Ashby

```{r ashby_rt}
ashby_rt_id <- merge(ashby_rt, id, by = "Subject", all.x = TRUE, all.y = FALSE)

ashby_dat <- ashby_rt_id %>%
  dplyr::select(Subject, System, ashby.t, flanker_eff_cs, switch_eff_tf, tol_acc_tf, tol_time_tf, nd_tf, ravens_tf) %>% 
  na.omit %>%
  head(264)  # take first 132 with full data


m0 <- lmer(ashby.t ~ 1 + (1|Subject), data = ashby_dat)
m1 <- lmer(ashby.t ~ System + (1|Subject), data = ashby_dat)
anova(m0,m1)
#m2 <- lmer(ashby.t ~ System + ravens_tf + (1|Subject), data = ashby_dat)
#anova(m1,m2)
#anova(m2)
m3 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf  + (1|Subject), data = ashby_dat)
anova(m1,m3)
anova(m3)
m4.1 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + flanker_eff_cs:System + (1|Subject), data = ashby_dat)
anova(m3, m4.1)
m4.2 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + switch_eff_tf:System + (1|Subject), data = ashby_dat)
anova(m3, m4.2)
m4.3 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + tol_acc_tf:System + (1|Subject), data = ashby_dat)
anova(m3, m4.3)
m4.4 <- lmer(ashby.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + nd_tf:System + (1|Subject), data = ashby_dat)
anova(m3, m4.4)
anova(m4.4)

ht <- ashby_dat$System=="hypothesis-testing"
as <- ashby_dat$System=="associative"

ht_mod <- lm(ashby.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = ashby_dat, subset = ht)
summary(ht_mod)
anova(ht_mod)

as_mod <- lm(ashby.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = ashby_dat, subset = as)
summary(as_mod)
anova(as_mod)

ggplot(ashby_dat, aes(nd_tf, ashby.t)) + geom_point() + theme_bw() + facet_grid(.~System) + stat_smooth(method = "lm", se = FALSE)

ggplot(ashby_dat, aes(tol_time_tf, ashby.t)) + geom_point() + theme_bw() + stat_smooth(method = "lm", se = FALSE)

# CELF ANALYSES

ashby_dat2 <- ashby_rt_id %>%
  dplyr::select(Subject, System, ashby.t, rs_tf, fs_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(ashby.t ~ 1 + (1|Subject), data = ashby_dat2)
m1 <- lmer(ashby.t ~ System + ravens_tf + (1|Subject), data = ashby_dat2)
anova(m0,m1)
m3 <- lmer(ashby.t ~ System + ravens_tf + rs_tf + fs_tf  + (1|Subject), data = ashby_dat2)
anova(m1,m3)
anova(m3)
summary(m3)
```


## Sloutsky


```{r sloutsky_rt}
sloutsky_rt_id <- merge(sloutsky_rt, id, by = "Subject", all.x = TRUE, all.y = FALSE)

sloutsky_dat <- sloutsky_rt_id %>%
  dplyr::select(Subject, System, sloutsky.t, flanker_eff_cs, switch_eff_tf, tol_acc_tf, tol_time_tf, nd_tf, ravens_tf, rs_tf, fs_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data


m0 <- lmer(sloutsky.t ~ 1 + (1|Subject), data = sloutsky_dat)
m1 <- lmer(sloutsky.t ~ System + (1|Subject), data = sloutsky_dat)
anova(m0,m1)
#m2 <- lmer(sloutsky.t ~ System + ravens_tf + (1|Subject), data = sloutsky_dat)
#anova(m1,m2)
#anova(m2)
m3 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf  + (1|Subject), data = sloutsky_dat)
anova(m1,m3)
anova(m3)
summary(m3)
m4.1 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + flanker_eff_cs:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.1)
m4.2 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + switch_eff_tf:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.2)
m4.3 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + tol_acc_tf:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.3)
anova(m4.3)
m4.4 <- lmer(sloutsky.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + nd_tf:System + (1|Subject), data = sloutsky_dat)
anova(m3, m4.4)

ht <- sloutsky_dat$System=="hypothesis-testing"
as <- sloutsky_dat$System=="associative"

ht_mod <- lm(sloutsky.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = sloutsky_dat, subset = ht)
summary(ht_mod)
anova(ht_mod)

as_mod <- lm(sloutsky.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = sloutsky_dat, subset = as)
summary(as_mod)
anova(as_mod)

ggplot(sloutsky_dat, aes(tol_time_tf, sloutsky.t)) + geom_point() + theme_bw() + stat_smooth(se = FALSE, method = "lm") + xlab("Planning (Tower of London accuracy)") + ylab("Sloutsky Reaction Time") + ggtitle("Significant interaction between ToL and system on Sloutsky RT") + facet_grid(.~System)

ggplot(sloutsky_dat, aes(ravens_tf, sloutsky.t)) + geom_point() + theme_bw() + stat_smooth(se = FALSE, method = "lm") + xlab("Nonverbal IQ") + ylab("Sloutsky Reaction Time") + ggtitle("Significant main effect of nonverbal IQ on Sloutsky RT")


# CELF ANALYSES

sloutsky_dat2 <- sloutsky_rt_id %>%
  dplyr::select(Subject, System, sloutsky.t, rs_tf, fs_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(sloutsky.t ~ 1 + (1|Subject), data = sloutsky_dat2)
m1 <- lmer(sloutsky.t ~ System + ravens_tf + (1|Subject), data = sloutsky_dat2)
anova(m0,m1)
m3 <- lmer(sloutsky.t ~ System + ravens_tf + rs_tf + fs_tf  + (1|Subject), data = sloutsky_dat2)
anova(m1,m3)
anova(m3)

```


## TT

```{r tt_rt}
tt_rt_id <- merge(tt_rt, id, by = "Subject", all.x = TRUE, all.y = FALSE)

tt_dat <- tt_rt_id %>%
  dplyr::select(Subject, System, tt.t, flanker_eff_cs, switch_eff_tf, tol_acc_tf, tol_time_tf, nd_tf, ravens_tf, rs_tf, fs_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(tt.t ~ 1 + (1|Subject), data = tt_dat)
m1 <- lmer(tt.t ~ System + (1|Subject), data = tt_dat)
anova(m0,m1)
#m2 <- lmer(tt.t ~ System + ravens_tf + (1|Subject), data = tt_dat)
#anova(m1,m2)
#anova(m2)
m3 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf  + (1|Subject), data = tt_dat)
anova(m1,m3)
anova(m3)
m4.1 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + flanker_eff_cs:System + (1|Subject), data = tt_dat)
anova(m3, m4.1)
anova(m4.1)
m4.2 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + switch_eff_tf:System + (1|Subject), data = tt_dat)
anova(m3, m4.2)
m4.3 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + tol_acc_tf:System + (1|Subject), data = tt_dat)
anova(m3, m4.3)
m4.4 <- lmer(tt.t ~ System + ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf + nd_tf:System + (1|Subject), data = tt_dat)
anova(m3, m4.4)

ht <- tt_dat$System=="hypothesis-testing"
as <- tt_dat$System=="associative"

ht_mod <- lm(tt.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = tt_dat, subset = ht)
summary(ht_mod)
anova(ht_mod)

as_mod <- lm(tt.t ~ ravens_tf + flanker_eff_cs + switch_eff_tf + tol_acc_tf + nd_tf, data = tt_dat, subset = as)
summary(as_mod)
anova(as_mod)

ggplot(tt_dat, aes(tol_time_tf, tt.t)) + geom_point() + theme_bw() + stat_smooth(se = FALSE, method = "lm") + xlab("Planning (Tower of London accuracy)") + ylab("tt Reaction Time") + ggtitle("Significant interaction between ToL and system on tt RT") + facet_grid(.~System)


# CELF ANALYSES

tt_dat2 <- tt_rt_id %>%
  dplyr::select(Subject, System, tt.t, rs_tf, fs_tf, ravens_tf) %>% 
  na.omit %>%
  head(264) # take first 132 with full data

m0 <- lmer(tt.t ~ 1 + (1|Subject), data = tt_dat2)
m1 <- lmer(tt.t ~ System + ravens_tf + (1|Subject), data = tt_dat2)
anova(m0,m1)
m3 <- lmer(tt.t ~ System + ravens_tf + rs_tf + fs_tf  + (1|Subject), data = tt_dat2)
anova(m1,m3)
anova(m3)
```




